movieDialoguesEnglish = [
"Frankly, my dear, I don't give a damn.",
"Bond ... James Bond",
"Baba Yaga .. He is man of utmost concerntration .",
"I'm going to make him an offer he can't refuse",
"My name is Fish Mooney, bitch!",
"Do you have any idea who you're talking to?",
"Friends don't lie.",
"I am the danger.",
"... then maybe your best course would be to tread lightly.",
"I am the one who knocks.",
"When you play the Game of Thrones, you win or you die.",
"If you want justice, you've come to the wrong place.",
"Valar Morghulis.",
"I demand a trial by combat!",
"Who wants to be king?",
"Winter is coming.",
"The Lannisters send their regards.",
"By order of the peaky blinders...",
"You know nothing Jon Snow.",
"Fear cuts deeper than swords.",
"Everything before the word ‘but’ is horseshit.",
"A lion doesn’t concern himself with the opinions of a sheep.",
"The man who passes the sentence should swing the sword.",
"Any man who must say ‘I am the king’ is no true king.",
"A ruler who kills those devoted to her is not a ruler who inspires devotion.",
"Never forget what you are. The rest of the world will not. Wear it like armour, and it can never be used to hurt you.",
"A Lannister always pays his debts.",
"Nothing f***s you harder than time.",
"All men must die, but we are not men",
"The night is dark and full of terrors",
"Dreams didnt make us kings , dragons did .... You motherfuckers!"
]