movieDialoguesTelugu = ["I like the way you breathe preethi ...",
"Common preethi dont do this to me !",
"I curse you to marry a tulu guy !",
"Veera Shankar Reddy… Mokke Kada Ani Peekeste Peeka Kostaa",
"Tappu Naa Vaipu Undi Kabatti Tala Dinchukuni Veltunna, Ledante Talalu Teesukellevaadni ",
"Chudu Oka Vaipe Chudu Inko Vaipu Chudalanukoku Tattukolevu",
"Naa Saavu Nenu Sasta Neekenduku",
"Atiga Aashapade Magavaadu… Atiga Aavashapade Aadadi Sukhapadinatlu Charitralo Ledu",
"Sar Sarle Enno Anukuntam… Anni Avutaya Enti",
"Okka Saari Commit Ayite Naa Maata Nene Vinanu",
"Evadu Kodite Dimma Tirigi Mind Block Ayipoddo Aade Pandu Gaadu ",
"Commissioner Kooturani Chepte Bhayapadipotama… Commissioner Kooturlani Preminchakudada… Commissioner Kooturlaki Mogudlu Raara",
"City Ki Entho Mandi Commissioner Lu Vastuntaru Pothuntaru.. Chanti Gaadu Eppudu Ikkade Untadu Local",
"Eppudochamani Kaadannayya Bullet Diginda Leda",
"Naa Peru Daya… Naku Lenide Adi",
"Iddaru Kottukunte Yuddham… Ade Okadu Meedadipothe Dandayaatra Idi Daya Gaadi Dandayaatra",
"Neeku Ego Lopale Untademo Naku Naa Chuttu Wifi La Untadi",
"Ooru Maarite Tine Food Maaruddi Padukune Bed Maaruddi Blood Enduku Maaruddi Ra Bloody Fool",
"Flute Jinka Mundu Oodu Simham Mundu Kaadu",
"Seat Kaadu Kada Assembly Gate Kuda Daatanivvanu",
"Any Centre Single Hand Ganesh",
"Mass Tho Pettukunte Madatha Madathadipoddi ",
"Tagore… Tongue Teguddi ",
"Na Daari Rahadari.. Better Don’t Come In My way ",
"Yuddham Chetakaanode Dharmam Gurinchi Maatladatadu Sir",
]